server:
  port: 8085

spring:
  application:
    name: msvc-connection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_PASSWORD}
  expiration: 86400000 # 1 día en ms